package com.myspace.git_hook_lab;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Request implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date date;
	private java.lang.String description;

	public Request() {
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public Request(java.util.Date date, java.lang.String description) {
		this.date = date;
		this.description = description;
	}

}